DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS overtime_request CASCADE;
DROP TABLE IF EXISTS daily_attendance CASCADE;
DROP TABLE IF EXISTS leave_request CASCADE;
DROP TABLE IF EXISTS employee_shift CASCADE;
